// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmvXyFqV8nrvTFwa2aPUFfC3T58o3kng',
    appId: '1:225798788368:web:f76cac7bae4e413e5b0195',
    messagingSenderId: '225798788368',
    projectId: 'buildairesume',
    authDomain: 'buildairesume.firebaseapp.com',
    storageBucket: 'buildairesume.firebasestorage.app',
    measurementId: 'G-CC29CH2Q7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxceIq6KseoDkOuyRF6roGR57LIhblAAk',
    appId: '1:225798788368:android:4d190fdcc647d5775b0195',
    messagingSenderId: '225798788368',
    projectId: 'buildairesume',
    storageBucket: 'buildairesume.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBa2StlZyJHSxQbdQqBKFi2jetDSF6BuY',
    appId: '1:225798788368:ios:f1cd569184efe6dd5b0195',
    messagingSenderId: '225798788368',
    projectId: 'buildairesume',
    storageBucket: 'buildairesume.firebasestorage.app',
    iosBundleId: 'tech.ttweb.buildairesume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBa2StlZyJHSxQbdQqBKFi2jetDSF6BuY',
    appId: '1:225798788368:ios:f1cd569184efe6dd5b0195',
    messagingSenderId: '225798788368',
    projectId: 'buildairesume',
    storageBucket: 'buildairesume.firebasestorage.app',
    iosBundleId: 'tech.ttweb.buildairesume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmvXyFqV8nrvTFwa2aPUFfC3T58o3kng',
    appId: '1:225798788368:web:ec9133dba8ed5f4f5b0195',
    messagingSenderId: '225798788368',
    projectId: 'buildairesume',
    authDomain: 'buildairesume.firebaseapp.com',
    storageBucket: 'buildairesume.firebasestorage.app',
    measurementId: 'G-S5FC6PXG0H',
  );
}
